//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyarGit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NyarGit.Properties.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Branch &apos;{0}&apos; does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BranchDoesNotExist {
            get {
                return ResourceManager.GetString("BranchDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to checkout branch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToCheckoutBranch {
            get {
                return ResourceManager.GetString("FailedToCheckoutBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to clone repository に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToCloneRepository {
            get {
                return ResourceManager.GetString("FailedToCloneRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to commit changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToCommitChanges {
            get {
                return ResourceManager.GetString("FailedToCommitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to pull changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToPullChanges {
            get {
                return ResourceManager.GetString("FailedToPullChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to push changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToPushChanges {
            get {
                return ResourceManager.GetString("FailedToPushChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error retrieving status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToRetrievingStatus {
            get {
                return ResourceManager.GetString("FailedToRetrievingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to stage changes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToStageChanges {
            get {
                return ResourceManager.GetString("FailedToStageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repository already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RepositoryAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryAlreadyExists", resourceCulture);
            }
        }
    }
}
